### ISSUE TITLE
Texture Management Change

### ISSUE THREAD

**Issue by ghost** [satoshinm/NetCraft#204]
Hi! How can I separate the textures and ~~read them by namespace id~~(found in item.c), and use texture by namespace not number?
There's a few blocks that are differentiated by extra number id, is there a way to do this?
Thanks.

**Comment by Huangtianhao06** [comment]
Oh I also changed the item.c in /src, maybe I shuffled some order and it just broke.
But Minecraft works with separated texture and JSON file (maybe later). And I want to do that.

**Comment by Huangtianhao06** [comment]
Texture seperated and namespace changed to namespace not number. But when I'm using small size textures, the displaying texture is smoothed out. I tried to use
```
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST)
glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST)
```
but didn't work

**Comment by Huangtianhao06** [comment]
fixed by using
```python
from pyglet.gl import (
    GL_NEAREST, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER,
    GL_TEXTURE_MIN_FILTER, glBindTexture, glTexImage2D, glTexParameteri)
from pyglet.image import Texture, load

def loadtexture(path):
    texture = TextureGroup(load(f'assets/live/textures/{path}.png').get_texture())
    glBindTexture(texture.texture.target, texture.texture.id)
    glTexParameteri(texture.texture.target, GL_TEXTURE_MAG_FILTER, GL_NEAREST)
    glTexParameteri(texture.texture.target, GL_TEXTURE_MIN_FILTER, GL_NEAREST)
    glBindTexture(texture.texture.target, 0)
    return texture
```
closed

**Comment by Huangtianhao06** [comment]
I've loaded the `assets/` and `data/` from vanilla Minecraft 20w06a, and now working on loading blockstate `.json` file. The way I solve texture problem is to declare a `dict` containing all textures with path as key and load them from `dict` when reading blockstate file. Just found that there's lots of library make for reading and writing nbt files. Any suggestions or algorithm about reading `.json` files would be helpful.
