### ISSUE TITLE
flower to stone

### ISSUE THREAD

**Issue by mat41997** [satoshinm/NetCraft#97]
flower change to stone

ss
![2017-05-06 11_10_42-netcraft](https://cloud.githubusercontent.com/assets/5884000/25771256/b55f98e0-324c-11e7-960d-2b6061031600.png)

**Comment by satoshinm** [comment]
Stone is translated as follows:

```java
125:        blocksToWeb.put("STONE", 6); 
136:        blocksToWeb.put("COBBLESTONE", 11);

397:            case 6: material = Material.STONE; break;
402:            case 11: material = Material.COBBLESTONE;
```

not sure how flowers are getting translated to stone, the default for untranslated materials is DIAMOND_ORE.

**Comment by satoshinm** [comment]
Tested all the flowers with [WebSandboxMC](https://github.com/satoshinm/WebSandboxMC) v1.0.3, relogged and the white flower (22) and blue flower (23) placed from the web client change to stone:

<img width="1038" alt="screen shot 2017-05-07 at 9 33 43 pm" src="https://cloud.githubusercontent.com/assets/26856618/25790394/fd731780-336c-11e7-8b23-0648f299086e.png">
<img width="1232" alt="screen shot 2017-05-07 at 9 33 57 pm" src="https://cloud.githubusercontent.com/assets/26856618/25790393/fd72cd84-336c-11e7-85fe-1114fbb74748.png">

**Comment by satoshinm** [comment]
There are more flower types in NetCraft than in Minecraft... I'll translate to red rose and yellow flower for now.
